apiVersion: v1
kind: Service
metadata:
  name: blog-web-app-backend
spec:
  clusterIP: None
  selector:
    app: blog-web-app-backend
  ports:
  - port: 3000
    targetPort: 3000
    name: blog-web-app-backend